name: macos
on: push

env:
  binary: libtesseract64.dylib

jobs:
  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
           brew install autoconf automake ninja    
    
    - name: Install lept
      run: |
           echo "Building leptonica..."
           git clone --depth 1 https://github.com/DanBloomberg/leptonica.git
           cd leptonica
           ./autogen.sh
           ./configure '--with-pic' '--disable-shared' '--without-zlib' '--without-jpeg' '--without-libtiff' '--without-giflib' '--without-libwebp' '--without-libwebpmux' '--without-libopenjpeg' '--disable-programs' 'CXX=clang++' 'CXXFLAGS=-g0 -O3'
           make
           make install

    - name: Install Tesseract
      run: |
           echo "Building Tesseract..."
           git clone --depth 1 --branch 5.2.0 https://github.com/tesseract-ocr/tesseract.git
           cd tesseract
           mkdir -p m4
           ./autogen.sh
           ./configure '--with-pic' '--disable-shared' '--disable-legacy' '--disable-graphics' '--disable-openmp' '--without-curl' '--without-archive' '--disable-doc' 'CXX=clang++' 'CXXFLAGS=-DTESS_EXPORTS -g0 -O3 -ffast-math'

    - name: Make and Install Tesseract
      run: |
           cd tesseract
           make -j 8
           sudo make install install

    - name: Build plugin
      run: |
           export C_INCLUDE_PATH=/usr/local/include
           export CPLUS_INCLUDE_PATH=/usr/local/include
           mkdir -p build
           cmake -S . -B build -G Ninja
           cmake --build build --config Release
           
    - uses: actions/upload-artifact@v3
      with:
          path: build/${{ env.binary }}
          retention-days: 5
