name: test
on: push

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Test
        run: |
          find / -name dumpbin.exe
          
      - uses: ilammy/msvc-dev-cmd@v1.11.0
      - name: Test
        run: |
          dumpbin
