name: windows
on: push

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          # - msystem: MINGW32
          #   mingw_package_prefix: mingw-w64-i686      
          #   libs: /mingw32/lib/
          #   libtesseract: libtesseract32.dll

          - msystem: MINGW64
            mingw_package_prefix: mingw-w64-x86_64
            libs: /mingw64/lib/
            libtesseract: libtesseract64.dll
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        install: >-
          autoconf 
          automake 
          automake-wrapper 
          git 
          libtool 
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
    
    - run: |
           pacman --noconfirm -S ${{ matrix.mingw_package_prefix }}-gcc

    - run: gcc --version

    - name: Install lept
      run: |
           echo "Building leptonica..."
           git clone --depth 1 https://github.com/DanBloomberg/leptonica.git
           cd leptonica
           ./autogen.sh
           ./configure '--with-pic' '--disable-shared' '--without-zlib' '--without-jpeg' '--without-libtiff' '--without-giflib' '--without-libwebp' '--without-libwebpmux' '--without-libopenjpeg' '--disable-programs' 'CXX=${{ matrix.config.cxx }}' 'CXXFLAGS=-g0 -O3 -static -static-libgcc -static-libstdc++'
           make
           make install

    - name: Install Tesseract
      run: |
           echo "Building Tesseract..."
           git clone --depth 1 --branch 5.2.0 https://github.com/tesseract-ocr/tesseract.git
           cd tesseract
           sed -e "s/#tesseract_LDADD += -ltiff//g" -i makefile.am
           ./autogen.sh
           ./configure '--with-pic' '--disable-shared' '--disable-legacy' '--disable-graphics' '--disable-openmp' '--without-curl' '--without-archive' '--disable-doc' 'CXX=${{ matrix.config.cxx }}' 'CXXFLAGS=-DTESS_EXPORTS -g0 -O3 -ffast-math -static -static-libgcc -static-libstdc++'
           make & make install

    - name: Build plugin
      run: |
           mkdir -p build
           cmake -S . -B build -G Ninja
           cmake --build build --config Release
           ls -R build

    - uses: actions/upload-artifact@v3
      with:
          name: ${{ env.libtesseract }}
          path: build/${{ env.libtesseract }}
          retention-days: 5
